### ISSUE TITLE
Publish DiffusionKit format checkpoints for FLUX

### ISSUE THREAD

**Issue by atiorh** [argmaxinc/DiffusionKit#19]
DiffusionKit currently patches the original FLUX checkpoint [here](https://github.com/argmaxinc/DiffusionKit/blob/main/python/src/diffusionkit/mlx/model_io.py#L85) each time the weights are restored. We should publish pre-patched checkpoints to avoid runtime reformatting.

**Comment by atiorh** [comment]
@arda-argmax  Feel free to close this issue by posting your latency stats.

**Comment by arda-argmax** [comment]
```
INFO:diffusionkit.mlx.model_io:Time to create model: 0.008893251419067383 s
INFO:diffusionkit.mlx.model_io:Time to load weights: 0.3058888912200928 s
INFO:diffusionkit.mlx.model_io:Time to adjust weights: 0.007555961608886719 s
```
Patching the checkpoint takes around 10 ms, which does not create significant latency.
