### ISSUE TITLE
benchmark-mode slower

### ISSUE THREAD

**Issue by 7enChan** [argmaxinc/DiffusionKit#22]
Hi, 
I tested this on my 96GB M2Max and found that the benchmark-mode is actually slower. The displayed "Total time: 32.731s" took more than a minute in reality, while without benchmark-mode, the displayed "Total time: 27.998s" took about 34 seconds.
During the run, there were some errors like "Failed to load _MLModelProxy: No module named 'coremltools.libcoremlpython'". I'm not sure if this is related to the performance difference.
Thanks!

Here is the detailed log：

### with --benchmark-mode
diffusionkit-cli --prompt "a bottle with a rainbow galaxy inside it on top of a wooden table on a table in the middle of a modern kitchen" --height 1024 --width 1024 --seed 2024 --step 2 --benchmark-mode --model-version FLUX.1-schnell
scikit-learn version 1.5.1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
Torch version 2.4.0 has not been tested with coremltools. You may run into unexpected errors. Torch 2.2.0 is the most recent version that has been tested.
Failed to load _MLModelProxy: No module named 'coremltools.libcoremlpython'
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Fail to import BlobWriter from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
WARNING:diffusionkit.mlx.scripts.generate_images:Disabling CFG for FLUX.1-schnell model.
WARNING:diffusionkit.mlx.scripts.generate_images:Benchmark mode is enabled, disabling low memory mode.
/Users/iam/miniconda3/envs/diffusionkit/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
INFO:diffusionkit.mlx.scripts.generate_images:Output image resolution will be 1024x1024
INFO:diffusionkit.mlx.scripts.generate_images:Running in benchmark mode. Warming up the models. (generated latents will be discarded)
INFO:diffusionkit.mlx:Seed: 2024
  0%|                                                     | 0/1 [00:00<?, ?it/s]INFO:diffusionkit.mlx.mmdit:Cached modulation_params for timesteps=array([1000, 0], dtype=bfloat16)
INFO:diffusionkit.mlx.mmdit:Cached modulation_params will reduce peak memory by 6.5 GB
100%|█████████████████████████████████████████████| 1/1 [00:09<00:00,  9.28s/it]
INFO:diffusionkit.mlx.scripts.generate_images:Benchmark mode: Warming up the models done.
INFO:diffusionkit.mlx:Pre text encoding peak memory: 38.636GB
INFO:diffusionkit.mlx:Pre text encoding active memory: 25.303GB
INFO:diffusionkit.mlx:Post text encoding peak memory: 38.636GB
INFO:diffusionkit.mlx:Post text encoding active memory: 25.305GB
INFO:diffusionkit.mlx:Text encoding time: 0.461s
INFO:diffusionkit.mlx:Pre denoise peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre denoise active memory: 25.305GB
INFO:diffusionkit.mlx:Seed: 2024
  0%|                                                     | 0/2 [00:00<?, ?it/s]INFO:diffusionkit.mlx.mmdit:Cached modulation_params for timesteps=array([1000, 500, 0], dtype=bfloat16)
INFO:diffusionkit.mlx.mmdit:Cached modulation_params will reduce peak memory by 6.5 GB
100%|█████████████████████████████████████████████| 2/2 [00:24<00:00, 12.04s/it]
INFO:diffusionkit.mlx:Post denoise peak memory: 31.359GB
INFO:diffusionkit.mlx:Post denoise active memory: 25.309GB
INFO:diffusionkit.mlx:Denoising time: 24.748s
INFO:diffusionkit.mlx:Pre decode peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre decode active memory: 25.309GB
INFO:diffusionkit.mlx:Post decode peak memory: 38.639GB
INFO:diffusionkit.mlx:Post decode active memory: 25.315GB
INFO:diffusionkit.mlx:============= Summary =============
INFO:diffusionkit.mlx:Text encoder: 0.5s
INFO:diffusionkit.mlx:Denoising: 24.7s
INFO:diffusionkit.mlx:Image decoder: 6.8s
INFO:diffusionkit.mlx:Peak memory: 38.6GB
INFO:diffusionkit.mlx:============= Inference Context =============
INFO:diffusionkit.mlx:Operating System:
{'os_build_number': '23G93', 'os_type': 'macOS', 'os_version': '14.6.1'}
INFO:diffusionkit.mlx:Device:
{'cpu_core_count': 12,
 'gpu_core_count': 38,
 'max_ram': '102177734656',
 'product_name': 'Apple M2 Max'}
INFO:diffusionkit.mlx:Total time: 32.731s
INFO:diffusionkit.mlx.scripts.generate_images:Saved the image to out.png

### without --benchmark-mode
~ % diffusionkit-cli --prompt "a bottle with a rainbow galaxy inside it on top of a wooden table on a table in the middle of a modern kitchen" --height 1024 --width 1024 --seed 2024 --step 2 --model-version FLUX.1-schnell
scikit-learn version 1.5.1 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
Torch version 2.4.0 has not been tested with coremltools. You may run into unexpected errors. Torch 2.2.0 is the most recent version that has been tested.
Failed to load _MLModelProxy: No module named 'coremltools.libcoremlpython'
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Fail to import BlobWriter from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
WARNING:diffusionkit.mlx.scripts.generate_images:Disabling CFG for FLUX.1-schnell model.
/Users/iam/miniconda3/envs/diffusionkit/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
INFO:diffusionkit.mlx.scripts.generate_images:Output image resolution will be 1024x1024
INFO:diffusionkit.mlx:Pre text encoding peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre text encoding active memory: 0.0GB
INFO:diffusionkit.mlx:Post text encoding peak memory: 0.964GB
INFO:diffusionkit.mlx:Post text encoding active memory: 0.476GB
INFO:diffusionkit.mlx:Text encoding time: 2.839s
INFO:diffusionkit.mlx:Pre denoise peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre denoise active memory: 0.002GB
INFO:diffusionkit.mlx:Seed: 2024
  0%|                                                     | 0/2 [00:00<?, ?it/s]INFO:diffusionkit.mlx.mmdit:Cached modulation_params for timesteps=array([1000, 500, 0], dtype=bfloat16)
INFO:diffusionkit.mlx.mmdit:Cached modulation_params will reduce peak memory by 6.5 GB
100%|█████████████████████████████████████████████| 2/2 [00:22<00:00, 11.16s/it]
INFO:diffusionkit.mlx:Post denoise peak memory: 19.06GB
INFO:diffusionkit.mlx:Post denoise active memory: 16.118GB
INFO:diffusionkit.mlx:Denoising time: 23.017s
INFO:diffusionkit.mlx:Pre decode peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre decode active memory: 0.003GB
INFO:diffusionkit.mlx:Post decode peak memory: 11.781GB
INFO:diffusionkit.mlx:Post decode active memory: 0.101GB
INFO:diffusionkit.mlx:============= Summary =============
INFO:diffusionkit.mlx:Text encoder: 2.8s
INFO:diffusionkit.mlx:Denoising: 23.0s
INFO:diffusionkit.mlx:Image decoder: 1.3s
INFO:diffusionkit.mlx:Peak memory: 19.1GB
INFO:diffusionkit.mlx:============= Inference Context =============
INFO:diffusionkit.mlx:Operating System:
{'os_build_number': '23G93', 'os_type': 'macOS', 'os_version': '14.6.1'}
INFO:diffusionkit.mlx:Device:
{'cpu_core_count': 12,
 'gpu_core_count': 38,
 'max_ram': '102177734656',
 'product_name': 'Apple M2 Max'}
INFO:diffusionkit.mlx:Total time: 27.998s
INFO:diffusionkit.mlx.scripts.generate_images:Saved the image to out.png

**Comment by atiorh** [comment]
@7enChan Thanks for the note!

> I tested this on my 96GB M2Max and found that the benchmark-mode is actually slower. The displayed "Total time: 32.731s" took more than a minute in reality,

This is expected as benchmark mode warms up the models by running each model once before the full image generation loop is executed. Time elapsed during model load and model warm-ups is a one-time start-up cost that is amortized across image generations.

> while without benchmark-mode, the displayed "Total time: 27.998s" took about 34 seconds.

Similarly, model loading during initialization takes several seconds as a one-time start-up cost.

**Comment by 7enChan** [comment]
> @7enChan Thanks for the note!
> 
> > I tested this on my 96GB M2Max and found that the benchmark-mode is actually slower. The displayed "Total time: 32.731s" took more than a minute in reality,
> 
> This is expected as benchmark mode warms up the models by running each model once before the full image generation loop is executed. Time elapsed during model load and model warm-ups is a one-time start-up cost that is amortized across image generations.
> 
> > while without benchmark-mode, the displayed "Total time: 27.998s" took about 34 seconds.
> 
> Similarly, model loading during initialization takes several seconds as a one-time start-up cost.

Understood, but I found that after running benchmark mode the first time, and then running benchmark mode again later, the generation didn't get any faster.
