### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by rapidarchitect** [argmaxinc/DiffusionKit#3]
On a MacBook Pro M2 Max
Followed the install directions
I get this when running the pip command 
 Could not find a version that satisfies the requirement mlx (from diffusionkit) (from versions: none)

**Comment by atiorh** [comment]
Hello! What is your Python version?

**Comment by rapidarchitect** [comment]
3.11 as specified in the setup directions

___________________________
Mike Hjorleifsson
***@***.***

This e-mail and any files transmitted with it are confidential and are intended solely for the use of the
individual entity to whom they are addressed. This communication may contain material protected by the
attorney-client privilege. If you are not the intended recipient or the person responsible for delivering the
e-mail to the intended recipient, be advised that you have received this e-mail in error and that any use,
dissemination, forwarding, printing or copying this e-mail or any file or files transmitted with it is strictly prohibited.

**Comment by sroettering** [comment]
Same issue for me on M1 Pro with Python 3.12.4

**Comment by yosun** [comment]
works fine on m3max Sonoma 14.5 (23F79) - note that u should be using python 3.11 via the conda environment: `conda create -n diffusionkit python=3.11 -y`
