### ISSUE TITLE
Invalid latent size?

### ISSUE THREAD

**Issue by ghost** [argmaxinc/DiffusionKit#32]
Attempting to run conversion example:
`python -m python.src.diffusionkit.tests.torch2coreml.test_mmdit --sd3-ckpt-path stabilityai/stable-diffusion-3-medium --model-version 2b -o ./ --latent-size {64, 128}`

and I run into error:
`test_mmdit.py: error: argument --latent-size: invalid int value: '{64,'`

I double-checked to see if I followed instructions correctly; and I'm not sure what I did wrong on my end

Also, is it feasible to convert Flux models?  I wasn't able to ascertain the version size & latent size for such

**Comment by arda-argmax** [comment]
You need to choose either `64` or `128` for the latent size. This command should work:
```
python -m python.src.diffusionkit.tests.torch2coreml.test_mmdit --sd3-ckpt-path stabilityai/stable-diffusion-3-medium --model-version 2b -o ./ --latent-size 64
```

Unfortunately, we only support `stable-diffusion-3-medium` for CoreML model conversion. Flux models will be supported in the future.
