### ISSUE TITLE
How to Adjust Flux Guidance?

### ISSUE THREAD

**Issue by andyw-0612** [argmaxinc/DiffusionKit#35]
Hi, this is a great project and I'm able to get Flux Dev up and running! However, I was wondering, since flux has their own guidance parameter and can influence generation style/quality quite a bit, different from the usual CFG, where can I adjust that?

**Comment by atiorh** [comment]
Hello @andyw-0612! I believe you are looking for [--cfg](https://github.com/argmaxinc/DiffusionKit/blob/main/python/src/diffusionkit/mlx/scripts/generate_images.py#L56).
