### ISSUE TITLE
Duplicated MMDiTConfig struct definition

### ISSUE THREAD

**Issue by ngaloppo** [argmaxinc/DiffusionKit#38]
Is this implementation of `MMDiTConfig` intentionally duplicated from the one in `diffusionkit.mlx.config.py`?

https://github.com/argmaxinc/DiffusionKit/blob/e63501d95e0aeafc1c31220a7262c6c74bdfc351/python/src/diffusionkit/torch/mmdit.py#L14

**Comment by arda-argmax** [comment]
Yes, we wanted to separate the `torch` and `mlx` implementations.
