### ISSUE TITLE
How to use the targeted model directory with diffusionkit-cli?

### ISSUE THREAD

**Issue by southkorea2013** [argmaxinc/DiffusionKit#5]
Hi,

I have finished setting of DiffusionKit. When I run the following command:
diffusionkit-cli --prompt "a photo of a cat" --output-path /Users/***/demos/DiffusionKit/cat.png --seed 0 --w16 --a16

I find the downloaded model is placed at ~/.cache/huggingface/hub/models--argmaxinc--stable-diffusion

I have already downloaded stabilityai/stable-diffusion-3-medium under the folder ~/models/stable-diffusion-3-medium

How to switch the diffusionkit-cli to my targeted folder  '~/models/stable-diffusion-3-medium'?

Thanks,
Nan

**Comment by arda-argmax** [comment]
Hi,
We merged [this](https://github.com/argmaxinc/DiffusionKit/pull/7) PR that added the following arg for `diffusionkit-cli`:

`--local-ckpt` : path to the local `sd3.safetensors` file.

You can now use your local model checkpoint.

Best,
Arda

**Comment by southkorea2013** [comment]
> Hi, We merged [this](https://github.com/argmaxinc/DiffusionKit/pull/7) PR that added the following arg for `diffusionkit-cli`:
> 
> `--local-ckpt` : path to the local `sd3.safetensors` file.
> 
> You can now use your local model checkpoint.
> 
> Best, Arda

Thanks.
