### ISSUE TITLE
colab t4

### ISSUE THREAD

**Issue by werruww** [argmaxinc/DiffusionKit#50]
INFO:diffusionkit.mlx.scripts.generate_images:Output image resolution will be 768x1360
INFO:diffusionkit.mlx:Pre text encoding peak memory: 0.0GB
INFO:diffusionkit.mlx:Pre text encoding active memory: 0.0GB
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Matmul::eval_cpu] Currently only supports float32.

**Comment by werruww** [comment]
!diffusionkit-cli --prompt "a cat"  --model-version argmaxinc/mlx-FLUX.1-schnell-4bit-quantized --steps 4 --height 768 --width 1360

**Comment by werruww** [comment]
!huggingface-cli login --token 
from diffusionkit.mlx import FluxPipeline
pipeline = FluxPipeline(
  shift=1.0,
  model_version="argmaxinc/mlx-FLUX.1-schnell", 
  low_memory_mode=True,
  a16=True,
  w16=True,
)

HEIGHT =32
WIDTH = 32
NUM_STEPS = 4  #  4 for FLUX.1-schnell, 50 for SD3 and FLUX.1-dev
CFG_WEIGHT = 0. # for FLUX.1-schnell, 5. for SD3

image, _ = pipeline.generate_image(
  "a photo of a cat",
  cfg_weight=CFG_WEIGHT,
  num_steps=NUM_STEPS,
  latent_size=(HEIGHT // 1, WIDTH // 1),
)

**Comment by werruww** [comment]
Makes Colab restart

**Comment by arda-argmax** [comment]
Our DiffusionKit MLX inference pipeline is currently optimized and tested exclusively for Apple Silicon devices (M1 and newer). Support for other platforms will be considered in the future and announced at a later date.
